# Generated by Django 5.1.3 on 2025-02-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreminder',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
