# Generated by Django 5.1.4 on 2025-03-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_deactivatedusers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientnote",
            name="note_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("generic", "Generic"),
                    ("medication", "Medication"),
                    ("age", "Age"),
                    ("sex", "Sex"),
                    ("height ", "Height"),
                ],
                default="generic",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientnote",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
