# Generated by Django 5.1.4 on 2025-03-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_squashed_0007_rename_patient_id_patientinfo_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinfo",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="medications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="other_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
