# Generated by Django 5.1.4 on 2025-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_patientinfo_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="alarm_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="shareable_id",
            field=models.CharField(
                blank=True, default=None, max_length=9, null=True, unique=True
            ),
        ),
    ]
