# Generated by Django 5.1.4 on 2025-03-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_is_verified_user_verification_token_and_more'),
        ('api', '0010_alter_user_shareable_id_notificationpreference'),
    ]

    operations = [
    ]
