# Generated by Django 5.1.3 on 2025-03-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_providernotification'),
        ('api', '0011_merge_20250329_1742'),
    ]

    operations = [
    ]
