# Generated by Django 5.1.3 on 2025-03-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20250329_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='text_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
